service: cart-api-serverless
frameworkVersion: "3"
provider:
  name: aws
  stage: dev
  runtime: nodejs16.x
  region: eu-west-1
  profile: epamlearn
  vpc:
    securityGroupIds:
      - sg-01f20cf09d0eed2dc
    subnetIds:
      - subnet-03f3f25b44c451613
      - subnet-05fe199163efa0247
      - subnet-0d90a15f70f84e353
  environment: ${file(env.json)}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
