service: import-service

frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  runtime: nodejs16.x
  region: eu-west-1
  profile: epamlearn
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:*
            - dynamodb:*
          Resource:
            - "arn:aws:dynamodb:eu-west-1:*:table/olek-products"
            - "arn:aws:dynamodb:eu-west-1:*:table/olek-stock"
            - "arn:aws:s3:::olek-import-service-s3/*"

  environment:
    PRODUCTS_DYNAMO_DB: 'olek-products'
    STOCK_DYNAMO_DB: 'olek-stock'
    UPLOADS_S3_BUCKET: 'olek-import-service-s3'
    SNS_TOPIC_ARN: !Ref createProductTopic
    SQS_URL: !GetAtt catalogItemsQueue.Arn

resources:
  Resources:
    createProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    emailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: oleksandr_pastukhov@epam.com
        Protocol: email
        TopicArn:
          Ref: createProductTopic
    catalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue

    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: olek-import-service-s3
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - POST

functions:
  catalogBatchProcess:
    handler: catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - catalogItemsQueue
              - Arn
          batchSize: 5
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.UPLOADS_S3_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
          rules:
              - prefix: uploaded/
              - suffix: .csv

  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                fileName: true
